### ISSUE TITLE
Design Files?

### ISSUE THREAD

**Issue by dabonetn** [jonn-reenthused/TI99-4A-dc-power-board#1]
I saw in your video that this is open source, are you going to post the actual design files?

I want to mod this for a 12V input, and then use a standard 7905 for the negative voltage out.
And maybe I can design a 3d bracket for a standard power input in place of the original psu input.

Thanks.

**Comment by jonn-reenthused** [comment]
I designed it in EasyEDA, i've added the exported schematic and PCB files so you should be able to import them on the site.

**Comment by jonn-reenthused** [comment]
I've also added the STL for a backplane barrel jack adaptor that Mr Lurch made
